In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  1.0842e-19  7.2908e-06
 1.5849e+29  8.4078e-45  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix



In [4]:
x = torch.rand(5, 3)
print(x)


 0.2089  0.3403  0.5286
 0.8834  0.8648  0.8870
 0.4024  0.9217  0.2127
 0.5693  0.4778  0.6398
 0.3459  0.4828  0.5688
[torch.FloatTensor of size 5x3]



Get its size



In [5]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [6]:
y = torch.rand(5, 3)
print(x + y)


 0.3295  0.5415  0.6705
 0.9462  0.9004  1.1739
 0.7937  1.7501  0.2758
 1.4897  1.0975  0.7133
 0.9073  0.7265  1.3463
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [7]:
print(torch.add(x, y))


 0.3295  0.5415  0.6705
 0.9462  0.9004  1.1739
 0.7937  1.7501  0.2758
 1.4897  1.0975  0.7133
 0.9073  0.7265  1.3463
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.3295  0.5415  0.6705
 0.9462  0.9004  1.1739
 0.7937  1.7501  0.2758
 1.4897  1.0975  0.7133
 0.9073  0.7265  1.3463
[torch.FloatTensor of size 5x3]



Addition: in-place



In [9]:
# adds x to y
y.add_(x)
print(y)


 0.3295  0.5415  0.6705
 0.9462  0.9004  1.1739
 0.7937  1.7501  0.2758
 1.4897  1.0975  0.7133
 0.9073  0.7265  1.3463
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [10]:
print(x[:, 1])


 0.3403
 0.8648
 0.9217
 0.4778
 0.4828
[torch.FloatTensor of size 5]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [11]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [12]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [13]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the torch Tensor automatically



In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [15]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y